---
- hosts: 3560test

  gather_facts: false
  connection: local

  tasks:
   - name: configure Gig2 settings
     ios_config:
       lines:
         - description test interface
         - ip address 10.0.0.1 255.255.255.0 
         - shut
       parents: interface GigabitEthernet1/0/2

       host: "{{ ansible_host }}"
       username: netman
       password: 1qaz@WSX
